### ISSUE TITLE
rhel9stig_lib_files_owner is undefined

### ISSUE THREAD

**Issue by wdower** [ansible-lockdown/RHEL9-STIG#115]
**Have you checked [ReadtheDocs](https://ansible-lockdown.readthedocs.io/en/latest/)?:** yes

**Describe the Issue**

Running the playbook fails on RHEL-09-232200 due to what appears to be an incorrect var name. Loop var is `rhel9stig_lib_files_owner` when it should probably be `discovered_lib_files_owner`.

**Expected Behavior**

Task RHEL-09-232200 completes.

**Actual Behavior**

```
TASK [roles/RHEL9-STIG : MEDIUM | RHEL-09-232200 | PATCH | RHEL 9 library files must be owned by root.] ***
       fatal: [localhost]: FAILED! => {"msg": "'rhel9stig_lib_files_owner' is undefined. 'rhel9stig_lib_files_owner' is undefined"}
```

I took at look at source and saw this for this task:
```yaml
- name: "MEDIUM | RHEL-09-232200 | PATCH | RHEL 9 library files must be owned by root."
  when: rhel_09_232200
  tags:
    - RHEL-09-232200
    - CAT2
    - CCI-001499
    - SRG-OS-000259-GPOS-00100
    - SV-257920r991560_rule
    - V-257920
    - NIST800-53R4_CM-5
  block:
    - name: "MEDIUM | RHEL-09-232200 | AUDIT | RHEL 9 library files must be owned by root."
      ansible.builtin.command: find -L /lib /lib64 /usr/lib /usr/lib64 ! -user root
      changed_when: false
      failed_when: discovered_lib_files_owner.rc not in [ 0, 1 ]
      register: discovered_lib_files_owner

    - name: "MEDIUM | RHEL-09-232200 | PATCH | RHEL 9 library files must be owned by root."
      when: discovered_lib_files_owner.stdout | length > 0
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
      loop: "{{ rhel9stig_lib_files_owner.stdout_lines }}"
```

It looks like the second task in the block should be looping over `discovered_lib_files_owner` since we just checked that it is populated.

**Control(s) Affected**
RHEL-09-232200
**Environment (please complete the following information):**

- branch being used: [e.g. devel] devel
- Ansible Version: [e.g. 2.10] 2.14
- Host Python Version: [e.g. Python 3.7.6] 3.9.18
- Ansible Server Python Version: [e.g. Python 3.7.6] 3.9.18
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Update the var name used in the loop attribute on the second task in the block
