### ISSUE TITLE
RHEL-09-252035 missing /etc/resolv.conf

### ISSUE THREAD

**Issue by jhomen368** [ansible-lockdown/RHEL9-STIG#25]
**Describe the Issue**
/etc/resolv.conf missing from system

**Expected Behavior**
/etc/resolv.conf should be generated from the /etc/resolv.conf.j2 not the other way around

**Actual Behavior**
/etc/resolv.conf doesn't get created

**Control(s) Affected**
RHEL-09-252035

**Environment (please complete the following information):**

- branch being used: v1R1
- Ansible Version: 2.15.5
- Host Python Version: 3.9
- Ansible Server Python Version: 3.9
- Additional Details:

**Additional Notes**

```
- name: "MEDIUM | RHEL-09-252035 | PATCH | RHEL 9 systems using Domain Name Servers (DNS) resolution must have at least two name servers configured."
      when:
        - rhel09stig_dns_nm_set is defined or
          rhel9stig_network_manager_dns.stdout == 'none' or
          rhel9stig_network_manager_dns.stdout == 'unmanaged'
      ansible.builtin.template:
        dest: /etc/resolv.conf.j2
        mode: '0644'
        src: /etc/resolv.conf
```

Looks like the src and dest are flipped.

**Possible Solution**
Enter a suggested fix here
