### ISSUE TITLE
RHEL-09-211050 fails in default RHEL9.4 install

### ISSUE THREAD

**Issue by PrymalInstynct** [ansible-lockdown/RHEL9-STIG#62]
**Describe the Issue**
In a default RHEL 9.4 Install the `/etc/systemd/system/ctrl-alt-del.target` file is sym linked to `reboot.target` which causes the systemd task that applies the systemd mask to fail.

**Expected Behavior**
I expect the task which modifies the systemd target for ctrl-alt-del to successfully become masked

**Actual Behavior**
The tasks fails

**Control(s) Affected**
RHEL-09-211050

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.17.5
- Host Python Version: 3.9.18
- Ansible Server Python Version: 3.12.7
- Additional Details:

**Additional Notes**
N/A

**Possible Solution**
Create additional task to ensure symlink is not present before masking the systemctl target

```
    - name: HIGH | RHEL-09-211050 | PATCH | The systemd Ctrl-Alt-Delete burst key sequence in RHEL 9 must be disabled | Remove symlink to reboot.target
      ansible.builtin.file:
        path: /etc/systemd/system/ctrl-alt-del.target
        state: absent
```

**Comment by uk-bolly** [comment]
hi @PrymalInstynct 

Thank you as always for the feedback, i'm not able to replicate the issue you are seeing
I have however changed the order and this is still working and idempotent which may help.

```
[root@rocky9bios ~]# ls -l /etc/systemd/system/ctrl-alt-del.target
lrwxrwxrwx. 1 root root 37 Nov 12 09:02 /etc/systemd/system/ctrl-alt-del.target -> /usr/lib/systemd/system/reboot.target
[root@rocky9bios ~]# systemctl status ctrl-alt-del.target
○ reboot.target - System Reboot
     Loaded: loaded (/usr/lib/systemd/system/reboot.target; enabled; preset: enabled)
     Active: inactive (dead)
       Docs: man:systemd.special(7)
```

New layout

```
  block:
    - name: HIGH | RHEL-09-211050 | PATCH | The systemd Ctrl-Alt-Delete burst key sequence in RHEL 9 must be disabled | Create symlink to /dev/null
      ansible.builtin.file:
        dest: /etc/systemd/system/ctrl-alt-del.target
        src: /dev/null
        state: link

    - name: HIGH | RHEL-09-211050 | PATCH | The systemd Ctrl-Alt-Delete burst key sequence in RHEL 9 must be disabled | systemctl disable
      ansible.builtin.systemd:
        #enabled: false
        masked: true
        name: ctrl-alt-del.target
        state: stopped
```

This gives the following

```
[root@rocky9bios ~]# ls -l /etc/systemd/system/ctrl-alt-del.target
lrwxrwxrwx. 1 root root 9 Nov 12 09:03 /etc/systemd/system/ctrl-alt-del.target -> /dev/null
[root@rocky9bios ~]# systemctl status ctrl-alt-del.target
○ ctrl-alt-del.target
     Loaded: masked (Reason: Unit ctrl-alt-del.target is masked.)
     Active: inactive (dead)
```

If you could possibly test and see if that solves your issue?

Many thanks as always

uk-bolly
